### ISSUE TITLE
iOS: Widget size in InAppBrowser

### ISSUE THREAD

**Issue by RaskaSG** [k-rudy/phonegap-twitter-timeline#1]
Hello,

Is there a way to control the size of the widget when loading it in the InAppBrowser plugin for iOS? Right now it only takes up about half of the total height of the page, leaving white space at the bottom.

Thanks!

**Comment by k-rudy** [comment]
hey, @RaskaSG what phonegap version are you using, what is the version of the target iOS?

**Comment by k-rudy** [comment]
closing for now, feel free to reopen if it's still the case
