### ISSUE TITLE
Page not found error.

### ISSUE THREAD

**Issue by gurindernarang** [k-rudy/phonegap-twitter-timeline#2]
Hi, i had integrated this plugin in my app which is on Play Store and itunes. but from past 2-3 days, it shows me Page not found error. Please fix as soon as possible.
![screenshot_20151202-171307](https://cloud.githubusercontent.com/assets/10511236/11552569/1a62fb1e-99ac-11e5-8593-cc25e82a6ec1.png)

**Comment by k-rudy** [comment]
@gurindernarang thanks for the report. The issue seems to be caused by recent Jekyll updates which is used as an engine for github pages. 

Please put slash `/` in front of widget parameter in the URL. i.e. your URL should look like the following: http://k-rudy.github.io/phonegap-twitter-timeline/?410453165654278145

Let me know if that helps

**Comment by Jeremy-Swanston** [comment]
Hi, I am having some issues getting the code to function properly in my app. Here is the break down of how I have the file setup:
- The InAppBrowser plugin (`<gap:plugin` name="org.apache.cordova.inappbrowser" />`) is included in the config.xml file. 
- I loaded `<script src="phonegap.js"></script> and <script src="cordova.js"></script>` within the `head` tag on the index.html file. 
- I created the widget on Twitter and copied the ID number. 
- I would like to have this load from the main navigation, so when you click on the button the Twitter feed will show. This is what the code looks like for this: `<a href="#" ontouchend="window.open(encodeURI('http://k-rudy.github.io/phonegap-twitter-timeline/?689914049081974784'), '_blank', 'location=no');">LINK NAME</a>`

As of now, when you click on this now only a white screen appears and there is no way to go back to the main homepage. Any thoughts on where I am going wrong would be greatly appreciated. Thank you!

**Comment by k-rudy** [comment]
@Jeremy-Swanston what version of PhoneGap are you using, what's the device and it's OS version where you're trying to run this? I would start from:
1. Trying to paste the link `http://k-rudy.github.io/phonegap-twitter-timeline/?689914049081974784` to your browser location and see if it opens. If it doesn't - you may have internet connectivity issues
2. if 1. works - try another target OS version, target device type.

**Comment by Jeremy-Swanston** [comment]
@k-rudy I am using PhoneGap for iOS 3.9.1. The device is an iPhone 6 and the OS is 9.2.1. I also tested this on an iPhone 5 with 9.2.1, but the results are the same - blank white screen. 

I tested the link in a browser and the Twitter feed showed up successfully. Does the code setup appear to be accurate. Many thanks for the help!

**Comment by Jeremy-Swanston** [comment]
@k-rudy I wanted to let you know that I got the code working! I made a modification to the InnAppBrowser plugin located within the config.xml file by adding the specified url to the `<allow-intent href=>`section. Previously, I was using `http://*/*`to allow for all sites, but the specific link addition seemed to do the trick. Thanks for your assistance.

**Comment by k-rudy** [comment]
@Jeremy-Swanston glad it's solved :+1:
