### ISSUE TITLE
Feed displays a blank screen

### ISSUE THREAD

**Issue by Jeremy-Swanston** [k-rudy/phonegap-twitter-timeline#3]
Hello @k-rudy,

I just updated a Phonegap app that is using your twitter timeline and noticed that the page is displaying a blank screen (see attached screenshot). The last update to the app was in August and the feed was displaying correctly. Just wanted to reach out to see if you had any thoughts on how to get it back.

Thanks!

![img_5439](https://user-images.githubusercontent.com/7013319/48501600-2cdc9680-e803-11e8-8006-91dce05d4913.PNG)

**Comment by k-rudy** [comment]
Hey, @Jeremy-Swanston thanks for the report. Could you please provide a bit more info on what is your widget url, what version of Phonegap, iOS are you using? Also it would help a lot in case you're doing android builds as well, to know if the Android version has the same issue. As  the first thing I would suggest checking your twitter preferences to make sure the widget you have created is still there. Thank you.

**Comment by Jeremy-Swanston** [comment]
Hi @k-rudy, thanks for getting back to me. I am using Phonegap cli-8.0.0 and the build is for both iOS and Android - both displaying the same blank screen. I see on Twitter that they no longer allow users to manage embedded timelines through account settings. Users now have to use [Twitter Publish](https://publish.twitter.com/#). This must be what it causing the issue.

**Comment by k-rudy** [comment]
@Jeremy-Swanston I have adjusted the service to support the new way of using the Twitter Publish. Basically all you need is to change `widget_id` in the url to the service to `twitter_username` of the page you want to embed. I.e. the url will look like the following: https://k-rudy.github.io/phonegap-twitter-timeline/?roodyruby. Please let me know if it helps.
